apiVersion: v2
name: kubernetes-nginx-operator
description: An example of Kubernetes operator that deploys nginx
type: application
version: 0.0.1
appVersion: 0.0.1
home: https://github.com/LuciferInLove/kubernetes-nginx-operator
maintainers:
  - name: LuciferInLove
    url: https://github.com/LuciferInLove
keywords:
  - kubernetes-operator
  - kubebuilder
dependencies:
  - name: cert-manager
    version: v1.7.1
    repository: https://charts.jetstack.io
    condition: installDependencies
  - name: nginx-ingress
    version: 1.41.3
    repository: https://charts.helm.sh/stable
    condition: installDependencies
