kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubernetes-nginx-operator.fullname" . }}
  labels:
    {{- include "kubernetes-nginx-operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubernetes-nginx-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "kubernetes-nginx-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
