apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubernetes-nginx-operator.fullname" . }}
  labels:
    {{- include "kubernetes-nginx-operator.labels" . | nindent 4 }}
spec:
  sessionAffinity: None
  type: ClusterIP
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    {{- include "kubernetes-nginx-operator.selectorLabels" . | nindent 4 }}
